import NavBar from "@/components/NavBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../styles/global.css'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <link href='https://fonts.googleapis.com/css?family=Bubblegum Sans' rel='stylesheet'/>

      <NavBar />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
